name: npm test, docker build and publish
on:
  push:
    branches:
      - master
 
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      - run: docker build -t truefeel/complexfib -f ./client/Dockerfile.dev ./client  
      - run: docker run -e CI=true truefeel/complexfib npm test
      - run: docker build -t truefeel/multi-client ./client 
      - run: docker build -t truefeel/multi-nginx ./nginx 
      - run: docker build -t truefeel/multi-server ./server 
      - run: docker build -t truefeel/multi-worker ./worker
      - uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions-hub/docker@master
        with:
          args: push truefeel/multi-client
      - uses: actions-hub/docker@master
        with:
          args: push truefeel/multi-nginx
      - uses: actions-hub/docker@master
        with:
          args: push truefeel/multi-server
      - uses: actions-hub/docker@master
        with:
          args: push truefeel/multi-worker