name: npm test, docker build and publish
on:
  push:
    branches:
      - master
 
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      - run: docker build -t truefeel/complexfib -f ./client/Dockerfile.dev ./client  
      - run: docker run -e CI=true truefeel/complexfib npm test
      - run: docker build -t truefeel/multi-client ./client 
      - run: docker build-t truefeel/multi-nginx ./nginx 
      - run: docker build-t truefeel/multi-server ./server 
      - run: docker build-t truefeel/multi-worker ./worker
      - name: docker push client
        uses: actions/docker/cli@master
        with:
          args: push truefeel/multi-client
      - name: docker push nginx
        uses: actions/docker/cli@master
        with:
          args: push truefeel/multi-nginx
      - name: docker push server
        uses: actions/docker/cli@master
        with:
          args: push truefeel/multi-server
      - name: docker push worker
        uses: actions/docker/cli@master
        with:
          args: push truefeel/multi-worker